# Generated by Django 4.0.6 on 2022-11-13 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_postmodel_data_alter_postmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='datafiles/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['csv', 'json', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='metadata',
            field=models.FileField(null=True, upload_to='metafiles/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['csv', 'json', 'zip'])]),
        ),
    ]
