# Generated by Django 4.0.6 on 2022-11-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_postmodel_image_remove_postmodel_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
